name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 0.1.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: git@github.com:ynhj123/flutter_ume.git
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
