name: flutter_ume_kit_console
description: Show debugPrint kit for flutter_ume.
version: 1.2.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.2.2
  flutter_ume:
    git:
      url: git@github.com:ynhj123/flutter_ume.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
