name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 1.2.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/ynhj123/flutter_ume.git
  touch_indicator: ^2.0.0

  # for Cyclop
  image: ^4.1.7
  quiver: ^3.2.1
  basics: ">=0.6.0 <0.11.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
