name: flutter_ume_kit_dio
description: Dio kit for flutter_ume.
version: 1.1.0
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/ynhj123/flutter_ume.git

  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
